#
#
GET http://localhost:8080/api/config/1
#
#

POST http://localhost:8080/api/config
Content-Type: application/json
{
    "water_porc": 70,
    "amount_porc": 20
}
#
#
PUT http://localhost:8080/api/config/1
Content-Type: application/json
{
    "water_porc": 70,
    "amount_porc": 20
}
#
#
GET http://localhost:8080/api/detail/
